// <auto-generated />
using System;
using BusinessTripAdmin.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessTripAdmin.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220403170203_DataSeeding")]
    partial class DataSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BusinessTripAdmin.Infrastructure.Data.DbModels.Allowance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AccomodationAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DailyAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Allowances");
                });

            modelBuilder.Entity("BusinessTripAdmin.Infrastructure.Data.DbModels.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9de0b25e-09dd-4d3d-86a1-ed131a5624da"),
                            CountryName = "AUSTRALIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Australian Dollar",
                            CurrencyCode = 4
                        },
                        new
                        {
                            Id = new Guid("6d3afe47-e20b-4b61-b57d-274e55be1235"),
                            CountryName = "AUSTRIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("054ae920-822c-4887-980b-2f90057be323"),
                            CountryName = "AZERBAIJAN",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("704886d4-45a9-49ad-990d-8e2f8db8bcc5"),
                            CountryName = "ALBANIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("e033413a-7eb6-4d9a-a731-d62fe5d6d62f"),
                            CountryName = "ALGERIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("8f0c2d33-34cf-4a70-8260-18e4c888247a"),
                            CountryName = "ANGOLA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("5bebe8d1-1d0c-4294-a518-e07df509f201"),
                            CountryName = "ARGENTINA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("c198fd37-7611-48d9-ad22-f0272cf05a25"),
                            CountryName = "ARMENIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("81e490d8-8569-4872-8449-d00b917625b6"),
                            CountryName = "AFGHANISTAN",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("f35f9a86-3653-40e7-88a7-8873fd960ee0"),
                            CountryName = "BANGLADESH",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("fa448394-0b93-4935-bcfc-a29b6734b134"),
                            CountryName = "BELARUS",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("9ec06ecc-545a-466e-aed0-1c9f2dd100a8"),
                            CountryName = "BELGIUM",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("e59c32c3-6b48-46f2-9d93-2753e3348812"),
                            CountryName = "BOSNIA AND HERZEGOVINA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("2d9da4bb-fb82-4482-908a-6ac3b5bf2a4a"),
                            CountryName = "BRAZIL",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("8bd41c75-33bb-41b4-b257-dd8e3ea6879c"),
                            CountryName = "UNITED KINGDOM",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Pound Sterling",
                            CurrencyCode = 5
                        },
                        new
                        {
                            Id = new Guid("71e72b19-8639-4804-9f01-c00feb87cf03"),
                            CountryName = "VIETNAM",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("e2ce2fc4-efab-426e-b24f-ef235a21c7a8"),
                            CountryName = "GHANA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("b940f8d6-0a41-489a-aab5-d6d64c06dc7a"),
                            CountryName = "GERMANY",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("f06ff73b-a2c4-46f3-b33d-d6074a2a4731"),
                            CountryName = "GIBRALTAR",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("f96eb017-5ace-4451-b93a-d6d3cc5a773e"),
                            CountryName = "GEORGIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("94440f56-8a73-4b2c-b63e-acd1126728ab"),
                            CountryName = "GREECE",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("17d16d90-0c4e-491a-979b-76a5146f2808"),
                            CountryName = "DENMARK",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("14b0a82b-c9b7-4dd9-9ec1-6bdbadf3ae6e"),
                            CountryName = "EGYPT",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("3c9bb88b-dff9-4c39-b7e5-6b3914f52ef4"),
                            CountryName = "ESTONIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("ae11fa10-a146-4ddc-a914-6010a01604dd"),
                            CountryName = "ETHIOPIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("0de631d5-466d-40a8-ac06-08ef082cd1a0"),
                            CountryName = "CONGO",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("fb634b20-aafa-409c-8a82-1325e5b26a3e"),
                            CountryName = "ZIMBABWE",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("573b03c1-c997-4fa3-b46f-089fdad19cd5"),
                            CountryName = "ISRAEL",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("b08c34dc-e20b-41c6-a073-4293eaf01d3c"),
                            CountryName = "INDIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("2020a24b-88a3-4c46-ba40-bc64b81ce093"),
                            CountryName = "INDONESIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("235d64bb-3fbf-4cc7-be87-89e1abef61cd"),
                            CountryName = "IRAQ",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("8ff5374a-0081-46f1-94d5-5e4e9525a223"),
                            CountryName = "IRAN",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("bfc163c9-f937-4ac1-97eb-7aac7a0689fd"),
                            CountryName = "IRELAND",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("4ee4e347-3026-4edb-b72f-280f0c286200"),
                            CountryName = "ICELAND",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("cafa0d04-ca34-4e5b-8af2-e576d2dee32a"),
                            CountryName = "SPAIN",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("f0ec1a1a-9cc1-4e20-b33f-841e95ba9515"),
                            CountryName = "ITALY",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("179bc570-ff28-4188-8062-8beca0674888"),
                            CountryName = "YEMEN",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("f2d04b05-8b94-4cdb-9925-bc68ada21950"),
                            CountryName = "JORDAN",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("9fb2ceb7-9fcc-43fc-b645-4513247f10ef"),
                            CountryName = "KAZAKHSTAN",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("f945938b-d3aa-4c55-b534-4be99a32ff17"),
                            CountryName = "CANADA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("a480ab84-5a04-4a16-b136-c4e8f2ede1e8"),
                            CountryName = "KENYA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("b6c4a8fa-1f92-4c2a-b0d0-71c9db72a8be"),
                            CountryName = "CYPRUS",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("3d68d5c0-ca83-49e4-adb0-548cadf9b465"),
                            CountryName = "KYRGYZSTAN",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("c0f550b1-1466-4fbc-b740-07737dbf74c7"),
                            CountryName = "CHINA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("8b73da44-a5f8-4db4-9b36-92f9bad886d9"),
                            CountryName = "NORTH KOREA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("38f13134-269b-4918-b857-4b69f617063e"),
                            CountryName = "COLOMBIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("b065dc2f-00aa-4af8-aca6-1d37905f15c4"),
                            CountryName = "SOUTH KOREA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("6ebc7f7d-7181-4b75-a21b-5cc5a6bd8c07"),
                            CountryName = "COTE D'IVOIRE",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("7d2abafc-d5b8-46b6-963a-5451bd3b5cb6"),
                            CountryName = "CUBA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("e0f992c6-39ed-436d-b2c9-c1e32fcfcc91"),
                            CountryName = "KUWAIT",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("977f86b2-7ce2-4c89-8ace-f732dd7a8a14"),
                            CountryName = "LATVIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("9f5432e9-7f39-4ec0-8d34-07dd0da15613"),
                            CountryName = "LIBYAN ARAB JAMAHIRIYA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("35c5cb44-9b8a-4fb9-9cfc-cec8eb0ac673"),
                            CountryName = "LEBANON",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("12c08437-e23d-42ff-aa8e-c15cfc49cc1e"),
                            CountryName = "LITHUANIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("d8c54bdb-8df1-478b-af21-06c5a10f21a8"),
                            CountryName = "LIECHTENSTEIN",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("2d9af68d-e0c8-427f-9d40-b1631715f4e3"),
                            CountryName = "LUXEMBOURG",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("d2cad772-5120-4273-b42a-fa4239a15893"),
                            CountryName = "NORTH MACEDONIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("3e022d17-2837-4a91-8850-8123889ebddd"),
                            CountryName = "MALAYSIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("83c2f7a4-f4e2-4e21-8826-dfca9112acf7"),
                            CountryName = "MALI",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("eec177ce-7437-49f3-9918-da3694fcee5b"),
                            CountryName = "MALTA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("4d072d95-9483-4be7-98da-344b52cdd0bb"),
                            CountryName = "MOROCCO",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("fbb90b66-e567-4d8c-8854-4deefca312fc"),
                            CountryName = "MEXICO",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("b1318e0a-d111-4822-9c1d-073cea549b5e"),
                            CountryName = "MOZAMBIQUE",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("ceb1d3f1-925e-49d9-9cb2-352ce3259711"),
                            CountryName = "MOLDOVA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("83e0fe3e-bfa2-4bb3-8304-371bad7b4181"),
                            CountryName = "MONACO",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("7e2a0d8e-bf3e-459c-a931-8f5895cf74eb"),
                            CountryName = "MONGOLIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("7ad02002-d76c-4f78-bed8-6c77785ee068"),
                            CountryName = "NIGERIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("d994d35e-06b9-411d-bd13-7b706875d7d9"),
                            CountryName = "NICARAGUA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("4d9b9ffe-c165-428e-825e-dab1bb6b6bfd"),
                            CountryName = "NEW ZEALAND",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("81a795a3-1b74-4e10-89b1-7cd4081125f1"),
                            CountryName = "NORWAY",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("25207346-2489-4abf-b00a-d3d46661212f"),
                            CountryName = "UNITED ARAB EMIRATES",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("c684b19b-f8b9-41fb-bda1-528ba876c2b0"),
                            CountryName = "PAKISTAN",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("e92c981f-44f1-4879-8e69-bffb51b49d2f"),
                            CountryName = "PERU",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("f3bc7bbb-780f-460f-bf99-476736b8d5c0"),
                            CountryName = "POLAND",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("5b297d8e-3ab4-4e03-aa63-667314c145fa"),
                            CountryName = "PORTUGAL",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("928d8869-f99d-4496-b04c-9fa4e4806938"),
                            CountryName = "ROMANIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("347dc592-7e86-4c15-b59b-65d52e161a8d"),
                            CountryName = "RUSSIAN FEDERATION",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("a79549a0-ab5d-4d4d-a5d0-a97f0cabd0d3"),
                            CountryName = "SAN MARINO",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("2faa1655-a4e0-49a3-a905-71eb08ae01ad"),
                            CountryName = "SAUDI ARABIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("0c7fc53a-d085-4250-ac2b-12c6e6714a08"),
                            CountryName = "UNITED STATES",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("ebca05fb-0bd5-48b7-9c96-4864626f34a9"),
                            CountryName = "SINGAPORE",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("93c952ca-4dc7-412e-8578-ab870a18ef3f"),
                            CountryName = "SYRIAN ARAB REPUBLIC",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("34434a82-ec72-4a1c-94df-4f5b5032ac5e"),
                            CountryName = "SLOVAKIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("bcfc73c4-277b-4479-9899-a934bdde2dee"),
                            CountryName = "SLOVENIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("c3089d50-167e-41dc-86d0-b629d10117e4"),
                            CountryName = "TAJIKISTAN",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("b001e1c8-ec60-4d76-816c-00ca9befff02"),
                            CountryName = "TUNISIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("c989a377-4721-4829-81b6-7db047c32b1e"),
                            CountryName = "TURKMENISTAN",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("303f76e5-2460-4600-ae5c-795f084064a0"),
                            CountryName = "TURKEY",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("9f30b544-8639-468b-b275-e79e45bf8137"),
                            CountryName = "UZBEKISTAN",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("7d2804e7-e6ce-433d-bbf2-ea6fa21f3fb8"),
                            CountryName = "UKRAINE",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("b6190653-e7ef-4de6-939f-3c03d39ce83d"),
                            CountryName = "HUNGARY",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("49d80ff5-f4b3-4c99-99b8-6b9966b8d490"),
                            CountryName = "FINLAND",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("d779b169-c84a-442a-9d15-ee6dd788c177"),
                            CountryName = "FRANCE",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("ff0731c9-772f-428e-89fa-fe59fee1be85"),
                            CountryName = "NETHERLANDS",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("4e6d506c-87bd-460b-8756-c51ab4be2583"),
                            CountryName = "CROATIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("565bce56-6751-4692-913b-d7605aa88843"),
                            CountryName = "CZECH REPUBLIC",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("fbe06a69-5a09-4d52-b766-7749cd7c6e35"),
                            CountryName = "CHILE",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("c4918b22-f403-40c5-9e0f-98f793669206"),
                            CountryName = "SWITZERLAND",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Swiss Franc",
                            CurrencyCode = 6
                        },
                        new
                        {
                            Id = new Guid("84b9a341-7615-42f3-9767-29e66db3e586"),
                            CountryName = "SWEDEN",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("3a3af9bc-3a9e-414c-831c-0b37bccc46ba"),
                            CountryName = "SOUTH AFRICA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        },
                        new
                        {
                            Id = new Guid("432a67c7-518a-4a2c-aa47-82252ba5e023"),
                            CountryName = "SERBIA",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Euro",
                            CurrencyCode = 3
                        },
                        new
                        {
                            Id = new Guid("7b6aace4-731b-4528-903f-45404a9b463c"),
                            CountryName = "JAPAN",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "Yen",
                            CurrencyCode = 7
                        },
                        new
                        {
                            Id = new Guid("3817ffcf-14b6-4898-90ae-ab52d0f2cab8"),
                            CountryName = "ALL OTHER COUNTRIES",
                            CreatedDate = new DateTime(2022, 4, 3, 8, 2, 3, 0, DateTimeKind.Unspecified),
                            Currency = "US Dollar",
                            CurrencyCode = 1
                        });
                });

            modelBuilder.Entity("BusinessTripAdmin.Infrastructure.Data.DbModels.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BusinessTripAdmin.Infrastructure.Data.DbModels.EmployeeBusinessTrip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<string>("TripFrom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TripTo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeBusinessTrips");
                });

            modelBuilder.Entity("BusinessTripAdmin.Infrastructure.Data.DbModels.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocalCountry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("BusinessTripAdmin.Infrastructure.Data.DbModels.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("BusinessTripAdmin.Infrastructure.Data.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BusinessTripAdmin.Infrastructure.Data.DbModels.Allowance", b =>
                {
                    b.HasOne("BusinessTripAdmin.Infrastructure.Data.DbModels.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BusinessTripAdmin.Infrastructure.Data.DbModels.Employee", b =>
                {
                    b.HasOne("BusinessTripAdmin.Infrastructure.Data.DbModels.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BusinessTripAdmin.Infrastructure.Data.DbModels.EmployeeBusinessTrip", b =>
                {
                    b.HasOne("BusinessTripAdmin.Infrastructure.Data.DbModels.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BusinessTripAdmin.Infrastructure.Data.DbModels.Position", b =>
                {
                    b.HasOne("BusinessTripAdmin.Infrastructure.Data.DbModels.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BusinessTripAdmin.Infrastructure.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BusinessTripAdmin.Infrastructure.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessTripAdmin.Infrastructure.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BusinessTripAdmin.Infrastructure.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
